import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
        "Crear nuevo grupo": "Create new group",
        "Notificaciones": "Notifications",
        "Notificación 1": "Notification 1",
        "Notificación 2": "Notification 2",
        "Notificación 3": "Notification 3",
        "Nombre del Grupo": "Group name",
        "Miembros del grupo": "Group members",
        "Cerrar sesión": "Sign out",
        "Nuevo miembro": "New member",
        "Nuevo grupo": "New group",
        "Descripción": "Description",
        "Fecha": "Date",
        "Categoria": "Category",
        "Agregar Persona": "Add person",
        "Deuda": "Debt",
        "Seleccione nuevo usuario": "Select new user",
        "Agregar": "Add",
        "Gastos": "Expenses",
        "Añadir Gasto": "Add Expense",
        "Eliminar Gasto": "Delete Expense",
        "Liquidar": "Settle",
        "Liquidado": "Settled",
        "Nombre": "Name",
        "Pagado Por": "Paid by",
        "Monto": "Amount",
        "Moneda": "Currency",
        "Miembro": "Member",
        "Miembros": "Members",
        "Eliminar": "Delete",
        "Crear": "Create",
        "Cancelar": "Cancel",
        "Enviar": "Send",
        "Editar": "Edit",
        "Guardar": "Save",
        "Cerrar": "Close",
        "Eliminar Grupo": "Delete Group",
        "Elige a una persona": "Choose a person",
        "Viaje": "Travel",  
        "Comida": "Food",
        "Entretenimiento": "Entertainment",
        "Educacion": "Education",
        "Ayuda": "Help",
        "Alimentos": "Food",
        "Transporte": "Transport",
        "Salud": "Health",
        "General": "General",
        "Nuevo Pago": "New payment",
        "Nombre del pago": "Payment name",
        "Ingrese un Monto": "Enter an amount",
        "Elige una moneda": "Choose a currency",
        "¿Quién Pagó?": "Who paid?",
        "Seleccione una categoria": "Select a category",
        "Bienvenido a la aplicación de control de gastos Billy. Aquí te mostramos cómo usar la página web:": "Welcome to the Billy expense control application. Here we show you how to use the web page:",
        "Regístrate con tu nombre, apellido, correo electrónico y contraseña en la página de sign up": "Register with your name, last name, email and password on the sign up page",
        "Inicia sesión con tu correo electrónico y contraseña en la página de log in": "Log in with your email and password on the log in page",
        "En la página de inicio, verás tus grupos y podrás crear un nuevo grupo haciendo click en el botón 'crear nuevo grupo'": "On the home page, you will see your groups and you can create a new group by clicking on the 'create new group' button",
        "Dentro de un grupo, puedes añadir miembros haciendo click en el botón 'agregar persona' o eliminar un miembro haciendo click en el ícono del cesto. Además, puedes agregar gastos haciendo click en el botón 'agregar gasto'": "Within a group, you can add members by clicking on the 'add person' button or delete a member by clicking on the basket icon. Also, you can add expenses by clicking on the 'add expense' button",
        "Al añadir un gasto, podrás agregar su nombre, el precio (seleccionando la divisa correspondiente), miembro que lo pagó, categoría y cómo quiere ser divido entre los miembros del grupo": "When adding an expense, you can add its name, price (selecting the corresponding currency), member who paid it, category and how it wants to be divided among the group members",
        "La división de gastos puede ser en partes iguales o por porcentajes. Una vez añadido el gasto, las deudas se actualizarán entre los miembros del grupo automáticamente": "The division of expenses can be in equal parts or by percentages. Once the expense is added, the debts will be updated among the group members automatically",
        "Puedes liquidar los gastos haciendo click en el botón 'liquidar gasto', y las deudas se actualizarán en consecuencia. Si has agregado un gasto erroneamente, puedes eliminarlo haciendo click en el botón 'eliminar gasto'": "You can settle the expenses by clicking on the 'settle expense' button, and the debts will be updated accordingly. If you have added an expense erroneously, you can delete it by clicking on the 'delete expense' button",
        "Otros": "Others",
      // Add more translations as needed
    },
  },
  es: {
    translation: {
      "Crear nuevo grupo": "Crear nuevo grupo",
      "Notificaciones": "Notificaciones",
      "Notificación 1": "Notificación 1",
      "Notificación 2": "Notificación 2",
      "Notificación 3": "Notificación 3",
      "Nombre del Grupo": "Nombre del grupo",
      "Miembros del grupo": "Miembros del grupo",
      "Cerrar sesión": "Cerrar sesión",
      "Nuevo miembro": "Nuevo miembro",
      "Nuevo grupo": "Nuevo grupo",
      "Descripción": "Descripción",
      "Fecha": "Fecha",
      "Categoria": "Categoría",
      "Agregar Persona": "Agregar persona",
      "Deuda": "Deuda",
      "Seleccione nuevo usuario": "Seleccione nuevo usuario",
      "Agregar": "Agregar",
      "Gastos": "Gastos",
      "Añadir Gasto": "Añadir Gasto",
      "Eliminar Gasto": "Eliminar Gasto",
      "Liquidar": "Liquidar",
      "Liquidado": "Liquidado",
      "Nombre": "Nombre",
      "Pagado Por": "Pagado por",
      "Monto": "Monto",
      "Moneda": "Moneda",
      "Miembro": "Miembro",
      "Miembros": "Miembros",
      "Eliminar": "Eliminar",
      "Crear": "Crear",
      "Cancelar": "Cancelar",
      "Enviar": "Enviar",
      "Editar": "Editar",
      "Guardar": "Guardar",
      "Cerrar": "Cerrar",
      "Eliminar Grupo": "Eliminar Grupo",
      "Elige a una persona": "Elige a una persona",
      "Viaje": "Viaje",
      "Comida": "Comida",
      "Entretenimiento": "Entretenimiento",
      "Educacion": "Educación",
      "Ayuda": "Ayuda",
      "Alimentos": "Alimentos",
      "Transporte": "Transporte",
      "Salud": "Salud",
      "General": "General",
      "Nuevo Pago": "Nuevo pago",
      "Nombre del pago": "Nombre del pago",
      "Ingrese un Monto": "Ingrese un Monto",
      "Elige una moneda": "Elige una moneda",
      "¿Quién Pagó?": "¿Quién Pagó?",
      "Seleccione una categoria": "Seleccione una categoria",
      "Bienvenido a la aplicación de control de gastos Billy. Aquí te mostramos cómo usar la página web:": "Bienvenido a la aplicación de control de gastos Billy. Aquí te mostramos cómo usar la página web:",
      "Regístrate con tu nombre, apellido, correo electrónico y contraseña en la página de sign up": "Regístrate con tu nombre, apellido, correo electrónico y contraseña en la página de sign up",
      "Inicia sesión con tu correo electrónico y contraseña en la página de log in": "Inicia sesión con tu correo electrónico y contraseña en la página de log in",
      "En la página de inicio, verás tus grupos y podrás crear un nuevo grupo haciendo click en el botón 'crear nuevo grupo'": "En la página de inicio, verás tus grupos y podrás crear un nuevo grupo haciendo click en el botón 'crear nuevo grupo'",
      "Dentro de un grupo, puedes añadir miembros haciendo click en el botón 'agregar persona' o eliminar un miembro haciendo click en el ícono del cesto. Además, puedes agregar gastos haciendo click en el botón 'agregar gasto'": "Dentro de un grupo, puedes añadir miembros haciendo click en el botón 'agregar persona' o eliminar un miembro haciendo click en el ícono del cesto. Además, puedes agregar gastos haciendo click en el botón 'agregar gasto'",
      "Al añadir un gasto, podrás agregar su nombre, el precio (seleccionando la divisa correspondiente), miembro que lo pagó, categoría y cómo quiere ser divido entre los miembros del grupo": "Al añadir un gasto, podrás agregar su nombre, el precio (seleccionando la divisa correspondiente), miembro que lo pagó, categoría y cómo quiere ser divido entre los miembros del grupo",
      "La división de gastos puede ser en partes iguales o por porcentajes. Una vez añadido el gasto, las deudas se actualizarán entre los miembros del grupo automáticamente": "La división de gastos puede ser en partes iguales o por porcentajes. Una vez añadido el gasto, las deudas se actualizarán entre los miembros del grupo automáticamente",
      "Puedes liquidar los gastos haciendo click en el botón 'liquidar gasto', y las deudas se actualizarán en consecuencia. Si has agregado un gasto erroneamente, puedes eliminarlo haciendo click en el botón 'eliminar gasto'": "Puedes liquidar los gastos haciendo click en el botón 'liquidar gasto', y las deudas se actualizarán en consecuencia. Si has agregado un gasto erroneamente, puedes eliminarlo haciendo click en el botón 'eliminar gasto'",
      "Otros": "Otros",
      // Add more translations as needed

    },
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'es',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
